name: "Traefik Edge Router"
slug: "traefik",
#image: "docker.io/traefik",
version: "v2.10",
description: "Traefik is an open-source Edge Router that makes publishing your services a fun and easy experience. It receives requests on behalf of your system and finds out which components are responsible for handling them.",
url: "https://github.com/mkenfenheuer/hassio-addons/tree/master/traefik",
arch:
  - aarch64
  - amd64
  - armhf
ports:
  - 80:80
ports_description:
  - 5002/tcp MaryTTS and Rhasspy compatible API
ingress: true,
ingress_port: 8080


