global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
log:
  level: WARN
providers:
  file:
    directory: /config/traefik/
    watch: true
serversTransport:
  insecureSkipVerify: true
